// ============================================================
// VÉSZ auf Deutsch – Backend Worker
// Holt ungarische Notfallmeldungen (BM OKF RSS), übersetzt neue
// Ereignisse per KI und stellt sie unter /api/events als JSON bereit.
// Quelle der Rohdaten: BM Országos Katasztrófavédelmi Főigazgatóság (BM OKF)
// ============================================================

const NATIONAL_RSS = "https://www.katasztrofavedelem.hu/10466/RSS_VESZ";

const COUNTY_NAMES = [
  "Bács-Kiskun", "Baranya", "Borsod-Abaúj-Zemplén", "Békés",
  "Csongrád-Csanád", "Fejér", "Győr-Moson-Sopron", "Hajdú-Bihar",
  "Heves", "Jász-Nagykun-Szolnok", "Komárom-Esztergom", "Nógrád",
  "Pest", "Somogy", "Szabolcs-Szatmár-Bereg", "Tolna", "Vas",
  "Veszprém", "Zala"
];

// Bekannte Städte/größere Orte -> Landkreis (Auszug aus offizieller KSH-Ortschaftsliste
// + bekannte Großstädte). Nicht vollständig (3.178 Ortschaften insgesamt in Ungarn),
// deckt aber Städte und größere Orte ab, die realistisch in Meldungen vorkommen.
const SETTLEMENT_COUNTY = {
  "Nyugotszenterzsébet": "Baranya",
  "Felsőszenterzsébet": "Zala",
  "Baranyaszentgyörgy": "Baranya",
  "Szigetszentmiklós": "Pest",
  "Alsószenterzsébet": "Zala",
  "Esztergályhorváti": "Zala",
  "Lispeszentadorján": "Zala",
  "Magyarszentmiklós": "Zala",
  "Pusztaszentlászló": "Zala",
  "Tornyiszentmiklós": "Zala",
  "Szabadszentkirály": "Baranya",
  "Borsodszentgyörgy": "Borsod-Abaúj-Zemplén",
  "Hernádszentandrás": "Borsod-Abaúj-Zemplén",
  "Hódmezővásárhely": "Csongrád-Csanád",
  "Kiskunfélegyháza": "Bács-Kiskun",
  "Törökszentmiklós": "Jász-Nagykun-Szolnok",
  "Bánokszentgyörgy": "Zala",
  "Kerkaszentkirály": "Zala",
  "Magyarszerdahely": "Zala",
  "Nemesszentandrás": "Zala",
  "Szentgyörgyvölgy": "Zala",
  "Szentkozmadombja": "Zala",
  "Szentmargitfalva": "Zala",
  "Vasboldogasszony": "Zala",
  "Dunaszentbenedek": "Bács-Kiskun",
  "Szalkszentmárton": "Bács-Kiskun",
  "Egyházasharaszti": "Baranya",
  "Felsőszentmárton": "Baranya",
  "Bükkszentkereszt": "Borsod-Abaúj-Zemplén",
  "Rásonysápberencs": "Borsod-Abaúj-Zemplén",
  "Szentistvánbaksa": "Borsod-Abaúj-Zemplén",
  "Tornaszentandrás": "Borsod-Abaúj-Zemplén",
  "Iszkaszentgyörgy": "Fejér",
  "Baktalórántháza": "Szabolcs-Szatmár-Bereg",
  "Hajdúböszörmény": "Hajdú-Bihar",
  "Mosonmagyaróvár": "Győr-Moson-Sopron",
  "Sátoraljaújhely": "Borsod-Abaúj-Zemplén",
  "Balatonmagyaród": "Zala",
  "Mikekarácsonyfa": "Zala",
  "Nemessándorháza": "Zala",
  "Szentpéterfölde": "Zala",
  "Vindornyaszőlős": "Zala",
  "Zalaszentbalázs": "Zala",
  "Zalaszentgyörgy": "Zala",
  "Zalaszentlászló": "Zala",
  "Zalaszentlőrinc": "Zala",
  "Zalaszentmárton": "Zala",
  "Zalaszentmihály": "Zala",
  "Bácsszentgyörgy": "Bács-Kiskun",
  "Bugacpusztaháza": "Bács-Kiskun",
  "Jászszentlászló": "Bács-Kiskun",
  "Alsószentmárton": "Baranya",
  "Boldogasszonyfa": "Baranya",
  "Csonkamindszent": "Baranya",
  "Drávaszerdahely": "Baranya",
  "Hegyszentmárton": "Baranya",
  "Horváthertelend": "Baranya",
  "Keresztespuszta": "Baranya",
  "Magyarhertelend": "Baranya",
  "Mindszentgodisa": "Baranya",
  "Bodrogkeresztúr": "Borsod-Abaúj-Zemplén",
  "Boldogkőváralja": "Borsod-Abaúj-Zemplén",
  "Dédestapolcsány": "Borsod-Abaúj-Zemplén",
  "Sajólászlófalva": "Borsod-Abaúj-Zemplén",
  "Tornaszentjakab": "Borsod-Abaúj-Zemplén",
  "Fábiánsebestyén": "Csongrád-Csanád",
  "Mezőszentgyörgy": "Fejér",
  "Badacsonytomaj": "Veszprém",
  "Balassagyarmat": "Nógrád",
  "Balatonföldvár": "Somogy",
  "Berettyóújfalu": "Hajdú-Bihar",
  "Biharkeresztes": "Hajdú-Bihar",
  "Hajdúszoboszló": "Hajdú-Bihar",
  "Székesfehérvár": "Fejér",
  "Kunszentmiklós": "Bács-Kiskun",
  "Mezőkovácsháza": "Békés",
  "Alsónemesapáti": "Zala",
  "Hagyárosbörönd": "Zala",
  "Petrikeresztúr": "Zala",
  "Pusztamagyaród": "Zala",
  "Szentgyörgyvár": "Zala",
  "Tótszentmárton": "Zala",
  "Vonyarcvashegy": "Zala",
  "Zalaszentjakab": "Zala",
  "Felsőszentiván": "Bács-Kiskun",
  "Almáskeresztúr": "Baranya",
  "Bogádmindszent": "Baranya",
  "Drávakeresztúr": "Baranya",
  "Görcsönydoboka": "Baranya",
  "Gyöngyösmellék": "Baranya",
  "Kisszentmárton": "Baranya",
  "Siklósnagyfalu": "Baranya",
  "Tótszentgyörgy": "Baranya",
  "Bodrogkisfalud": "Borsod-Abaúj-Zemplén",
  "Boldogkőújfalu": "Borsod-Abaúj-Zemplén",
  "Felsőkelecsény": "Borsod-Abaúj-Zemplén",
  "Mezőnagymihály": "Borsod-Abaúj-Zemplén",
  "Sajószentpéter": "Borsod-Abaúj-Zemplén",
  "Fehérvárcsurgó": "Fejér",
  "Pusztaszabolcs": "Fejér",
  "Sárszentmihály": "Fejér",
  "Balatonalmádi": "Veszprém",
  "Balatonboglár": "Somogy",
  "Balatonkenese": "Veszprém",
  "Balmazújváros": "Hajdú-Bihar",
  "Bátonyterenye": "Nógrád",
  "Kazincbarcika": "Borsod-Abaúj-Zemplén",
  "Vásárosnamény": "Szabolcs-Szatmár-Bereg",
  "Pilisvörösvár": "Pest",
  "Zalaszentgrót": "Zala",
  "Balatongyörök": "Zala",
  "Cserszegtomaj": "Zala",
  "Csonkahegyhát": "Zala",
  "Kehidakustány": "Zala",
  "Lendvajakabfa": "Zala",
  "Murakeresztúr": "Zala",
  "Pusztaederics": "Zala",
  "Tótszerdahely": "Zala",
  "Zalaszentiván": "Zala",
  "Zalaszombatfa": "Zala",
  "Balotaszállás": "Bács-Kiskun",
  "Császártöltés": "Bács-Kiskun",
  "Nemesnádudvar": "Bács-Kiskun",
  "Petőfiszállás": "Bács-Kiskun",
  "Soltszentimre": "Bács-Kiskun",
  "Szabadszállás": "Bács-Kiskun",
  "Aranyosgadány": "Baranya",
  "Baranyahídvég": "Baranya",
  "Drávapalkonya": "Baranya",
  "Drávaszabolcs": "Baranya",
  "Egyházaskozár": "Baranya",
  "Felsőegerszeg": "Baranya",
  "Királyegyháza": "Baranya",
  "Kisjakabfalva": "Baranya",
  "Kovácsszénája": "Baranya",
  "Mecsekpölöske": "Baranya",
  "Somogyhárságy": "Baranya",
  "Székelyszabar": "Baranya",
  "Villánykövesd": "Baranya",
  "Bükkmogyorósd": "Borsod-Abaúj-Zemplén",
  "Cserépváralja": "Borsod-Abaúj-Zemplén",
  "Hejőkeresztúr": "Borsod-Abaúj-Zemplén",
  "Hernádszurdok": "Borsod-Abaúj-Zemplén",
  "Krasznokvajda": "Borsod-Abaúj-Zemplén",
  "Mezőkeresztes": "Borsod-Abaúj-Zemplén",
  "Pusztaradvány": "Borsod-Abaúj-Zemplén",
  "Sajókeresztúr": "Borsod-Abaúj-Zemplén",
  "Szirmabesenyő": "Borsod-Abaúj-Zemplén",
  "Tiszacsermely": "Borsod-Abaúj-Zemplén",
  "Tiszapalkonya": "Borsod-Abaúj-Zemplén",
  "Tornabarakony": "Borsod-Abaúj-Zemplén",
  "Tornyosnémeti": "Borsod-Abaúj-Zemplén",
  "Csanádalberti": "Csongrád-Csanád",
  "Ferencszállás": "Csongrád-Csanád",
  "Alsószentiván": "Fejér",
  "Bakonycsernye": "Fejér",
  "Nagykarácsony": "Fejér",
  "Sárszentágota": "Fejér",
  "Szabadbattyán": "Fejér",
  "Szabadegyháza": "Fejér",
  "Balatonfüred": "Veszprém",
  "Balatonfűzfő": "Veszprém",
  "Balatonlelle": "Somogy",
  "Bélapátfalva": "Heves",
  "Borsodnádasd": "Borsod-Abaúj-Zemplén",
  "Csanádpalota": "Csongrád-Csanád",
  "Dunaharaszti": "Pest",
  "Fehérgyarmat": "Szabolcs-Szatmár-Bereg",
  "Tiszaújváros": "Borsod-Abaúj-Zemplén",
  "Tiszavasvári": "Szabolcs-Szatmár-Bereg",
  "Zalaegerszeg": "Zala",
  "Babosdöbréte": "Zala",
  "Bázakerettye": "Zala",
  "Gáborjánháza": "Zala",
  "Homokkomárom": "Zala",
  "Iklódbördőce": "Zala",
  "Kerkabarabás": "Zala",
  "Kerkateskánd": "Zala",
  "Kisvásárhely": "Zala",
  "Lickóvadamos": "Zala",
  "Muraszemenye": "Zala",
  "Nagykapornak": "Zala",
  "Szécsisziget": "Zala",
  "Szentpéterúr": "Zala",
  "Szijártóháza": "Zala",
  "Vindornyafok": "Zala",
  "Vindornyalak": "Zala",
  "Zalaboldogfa": "Zala",
  "Zalaköveskút": "Zala",
  "Csólyospálos": "Bács-Kiskun",
  "Dunatetétlen": "Bács-Kiskun",
  "Fülöpszállás": "Bács-Kiskun",
  "Hercegszántó": "Bács-Kiskun",
  "Jakabszállás": "Bács-Kiskun",
  "Kerekegyháza": "Bács-Kiskun",
  "Nagybaracska": "Bács-Kiskun",
  "Pálmonostora": "Bács-Kiskun",
  "Alsómocsolád": "Baranya",
  "Babarcszőlős": "Baranya",
  "Belvárdgyula": "Baranya",
  "Botykapeterd": "Baranya",
  "Drávacsepely": "Baranya",
  "Hegyhátmaróc": "Baranya",
  "Hosszúhetény": "Baranya",
  "Kisasszonyfa": "Baranya",
  "Kisbeszterce": "Baranya",
  "Kővágószőlős": "Baranya",
  "Kozármisleny": "Baranya",
  "Lovászhetény": "Baranya",
  "Magyaregregy": "Baranya",
  "Magyarlukafa": "Baranya",
  "Magyarmecske": "Baranya",
  "Magyarsarlós": "Baranya",
  "Mecseknádasd": "Baranya",
  "Palotabozsok": "Baranya",
  "Pécsdevecser": "Baranya",
  "Siklósbodony": "Baranya",
  "Somogyhatvan": "Baranya",
  "Somogyviszló": "Baranya",
  "Szentkatalin": "Baranya",
  "Vásárosdombó": "Baranya",
  "Zengővárkony": "Baranya",
  "Abaújszolnok": "Borsod-Abaúj-Zemplén",
  "Bodrogolaszi": "Borsod-Abaúj-Zemplén",
  "Borsodivánka": "Borsod-Abaúj-Zemplén",
  "Borsodszirák": "Borsod-Abaúj-Zemplén",
  "Felsőberecki": "Borsod-Abaúj-Zemplén",
  "Felsőtelekes": "Borsod-Abaúj-Zemplén",
  "Füzérradvány": "Borsod-Abaúj-Zemplén",
  "Hejőszalonta": "Borsod-Abaúj-Zemplén",
  "Hernádnémeti": "Borsod-Abaúj-Zemplén",
  "Makkoshotyka": "Borsod-Abaúj-Zemplén",
  "Taktaharkány": "Borsod-Abaúj-Zemplén",
  "Tiszabábolna": "Borsod-Abaúj-Zemplén",
  "Tiszadorogma": "Borsod-Abaúj-Zemplén",
  "Tornakápolna": "Borsod-Abaúj-Zemplén",
  "Tornanádaska": "Borsod-Abaúj-Zemplén",
  "Zemplénagárd": "Borsod-Abaúj-Zemplén",
  "Királyhegyes": "Csongrád-Csanád",
  "Magyarcsanád": "Csongrád-Csanád",
  "Pusztamérges": "Csongrád-Csanád",
  "Kápolnásnyék": "Fejér",
  "Kincsesbánya": "Fejér",
  "Lajoskomárom": "Fejér",
  "Nádasdladány": "Fejér",
  "Ráckeresztúr": "Fejér",
  "Sárkeresztes": "Fejér",
  "Sárkeresztúr": "Fejér",
  "Vértesboglár": "Fejér",
  "Abaújszántó": "Borsod-Abaúj-Zemplén",
  "Dunaföldvár": "Tolna",
  "Dunaújváros": "Fejér",
  "Dunavarsány": "Pest",
  "Hajdúhadház": "Hajdú-Bihar",
  "Nagykanizsa": "Zala",
  "Nyíregyháza": "Szabolcs-Szatmár-Bereg",
  "Salgótarján": "Nógrád",
  "Szombathely": "Vas",
  "Kiskunhalas": "Bács-Kiskun",
  "Tiszakécske": "Bács-Kiskun",
  "Kiskunmajsa": "Bács-Kiskun",
  "Szentlőrinc": "Baranya",
  "Martonvásár": "Fejér",
  "Pannonhalma": "Győr-Moson-Sopron",
  "Szigethalom": "Pest",
  "Törökbálint": "Pest",
  "Boncodfölde": "Zala",
  "Csertalakos": "Zala",
  "Csörnyeföld": "Zala",
  "Eszteregnye": "Zala",
  "Gelsesziget": "Zala",
  "Hosszúvölgy": "Zala",
  "Kemendollár": "Zala",
  "Kozmadombja": "Zala",
  "Lendvadedes": "Zala",
  "Nagybakónak": "Zala",
  "Nagylengyel": "Zala",
  "Pókaszepetk": "Zala",
  "Pusztaapáti": "Zala",
  "Szentliszló": "Zala",
  "Zalaháshágy": "Zala",
  "Zalaistvánd": "Zala",
  "Zalamerenye": "Zala",
  "Zalasárszeg": "Zala",
  "Ágasegyháza": "Bács-Kiskun",
  "Bátmonostor": "Bács-Kiskun",
  "Dunaegyháza": "Bács-Kiskun",
  "Érsekcsanád": "Bács-Kiskun",
  "Harkakötöny": "Bács-Kiskun",
  "Soltvadkert": "Bács-Kiskun",
  "Szentkirály": "Bács-Kiskun",
  "Baranyajenő": "Baranya",
  "Dinnyeberki": "Baranya",
  "Drávaiványi": "Baranya",
  "Drávasztára": "Baranya",
  "Dunaszekcső": "Baranya",
  "Erdősmecske": "Baranya",
  "Fazekasboda": "Baranya",
  "Ivánbattyán": "Baranya",
  "Magyartelek": "Baranya",
  "Máriakéménd": "Baranya",
  "Nagyharsány": "Baranya",
  "Nagytótfalu": "Baranya",
  "Patapoklosi": "Baranya",
  "Somogyapáti": "Baranya",
  "Szentlászló": "Baranya",
  "Alsóberecki": "Borsod-Abaúj-Zemplén",
  "Alsótelekes": "Borsod-Abaúj-Zemplén",
  "Bodroghalom": "Borsod-Abaúj-Zemplén",
  "Bódvaszilas": "Borsod-Abaúj-Zemplén",
  "Borsodgeszt": "Borsod-Abaúj-Zemplén",
  "Bükkaranyos": "Borsod-Abaúj-Zemplén",
  "Csokvaomány": "Borsod-Abaúj-Zemplén",
  "Erdőhorváti": "Borsod-Abaúj-Zemplén",
  "Felsődobsza": "Borsod-Abaúj-Zemplén",
  "Felsőnyárád": "Borsod-Abaúj-Zemplén",
  "Felsőregmec": "Borsod-Abaúj-Zemplén",
  "Felsővadász": "Borsod-Abaúj-Zemplén",
  "Felsőzsolca": "Borsod-Abaúj-Zemplén",
  "Füzérkajata": "Borsod-Abaúj-Zemplén",
  "Füzérkomlós": "Borsod-Abaúj-Zemplén",
  "Gagyvendégi": "Borsod-Abaúj-Zemplén",
  "Gömörszőlős": "Borsod-Abaúj-Zemplén",
  "Györgytarló": "Borsod-Abaúj-Zemplén",
  "Hernádkércs": "Borsod-Abaúj-Zemplén",
  "Hernádpetri": "Borsod-Abaúj-Zemplén",
  "Hernádvécse": "Borsod-Abaúj-Zemplén",
  "Hidasnémeti": "Borsod-Abaúj-Zemplén",
  "Kovácsvágás": "Borsod-Abaúj-Zemplén",
  "Legyesbénye": "Borsod-Abaúj-Zemplén",
  "Lénárddaróc": "Borsod-Abaúj-Zemplén",
  "Nagyrozvágy": "Borsod-Abaúj-Zemplén",
  "Novajidrány": "Borsod-Abaúj-Zemplén",
  "Nyékládháza": "Borsod-Abaúj-Zemplén",
  "Olaszliszka": "Borsod-Abaúj-Zemplén",
  "Rakacaszend": "Borsod-Abaúj-Zemplén",
  "Révleányvár": "Borsod-Abaúj-Zemplén",
  "Rudolftelep": "Borsod-Abaúj-Zemplén",
  "Sajókápolna": "Borsod-Abaúj-Zemplén",
  "Sajópálfala": "Borsod-Abaúj-Zemplén",
  "Sajópüspöki": "Borsod-Abaúj-Zemplén",
  "Sárazsadány": "Borsod-Abaúj-Zemplén",
  "Serényfalva": "Borsod-Abaúj-Zemplén",
  "Szentistván": "Borsod-Abaúj-Zemplén",
  "Teresztenye": "Borsod-Abaúj-Zemplén",
  "Tibolddaróc": "Borsod-Abaúj-Zemplén",
  "Tiszaladány": "Borsod-Abaúj-Zemplén",
  "Tiszatardos": "Borsod-Abaúj-Zemplén",
  "Tiszatarján": "Borsod-Abaúj-Zemplén",
  "Vámosújfalu": "Borsod-Abaúj-Zemplén",
  "Ambrózfalva": "Csongrád-Csanád",
  "Derekegyház": "Csongrád-Csanád",
  "Ópusztaszer": "Csongrád-Csanád",
  "Sándorfalva": "Csongrád-Csanád",
  "Tiszasziget": "Csongrád-Csanád",
  "Újszentiván": "Csongrád-Csanád",
  "Alcsútdoboz": "Fejér",
  "Beloiannisz": "Fejér",
  "Lovasberény": "Fejér",
  "Magyaralmás": "Fejér",
  "Mezőkomárom": "Fejér",
  "Zichyújfalu": "Fejér",
  "Abádszalók": "Jász-Nagykun-Szolnok",
  "Albertirsa": "Pest",
  "Békéscsaba": "Békés",
  "Biatorbágy": "Pest",
  "Budakalász": "Pest",
  "Celldömölk": "Vas",
  "Füzesabony": "Heves",
  "Hajdúdorog": "Hajdú-Bihar",
  "Hajdúnánás": "Hajdú-Bihar",
  "Jászberény": "Jász-Nagykun-Szolnok",
  "Mezőkövesd": "Borsod-Abaúj-Zemplén",
  "Szentendre": "Pest",
  "Jánoshalma": "Bács-Kiskun",
  "Sárospatak": "Borsod-Abaúj-Zemplén",
  "Tiszafüred": "Jász-Nagykun-Szolnok",
  "Mátészalka": "Szabolcs-Szatmár-Bereg",
  "Becsvölgye": "Zala",
  "Dobronhegy": "Zala",
  "Egeraracsa": "Zala",
  "Felsőpáhok": "Zala",
  "Gellénháza": "Zala",
  "Gombosszeg": "Zala",
  "Gutorfölde": "Zala",
  "Gyenesdiás": "Zala",
  "Kerkafalva": "Zala",
  "Kerkakutas": "Zala",
  "Kistolmács": "Zala",
  "Kustánszeg": "Zala",
  "Ligetfalva": "Zala",
  "Magyarföld": "Zala",
  "Nemesapáti": "Zala",
  "Nemeshetés": "Zala",
  "Nemespátró": "Zala",
  "Orbányosfa": "Zala",
  "Pethőhenye": "Zala",
  "Petrivente": "Zala",
  "Pördefölde": "Zala",
  "Pórszombat": "Zala",
  "Semjénháza": "Zala",
  "Sümegcsehi": "Zala",
  "Tormafölde": "Zala",
  "Zalaigrice": "Zala",
  "Zalaszabar": "Zala",
  "Zalaszántó": "Zala",
  "Zalatárnok": "Zala",
  "Bácsborsód": "Bács-Kiskun",
  "Bácsszőlős": "Bács-Kiskun",
  "Érsekhalma": "Bács-Kiskun",
  "Felsőlajos": "Bács-Kiskun",
  "Fülöpjakab": "Bács-Kiskun",
  "Kéleshalom": "Bács-Kiskun",
  "Kisszállás": "Bács-Kiskun",
  "Kunfehértó": "Bács-Kiskun",
  "Kunszállás": "Bács-Kiskun",
  "Ladánybene": "Bács-Kiskun",
  "Lajosmizse": "Bács-Kiskun",
  "Nyárlőrinc": "Bács-Kiskun",
  "Öregcsertő": "Bács-Kiskun",
  "Tiszaalpár": "Bács-Kiskun",
  "Almamellék": "Baranya",
  "Apátvarasd": "Baranya",
  "Bodolyabér": "Baranya",
  "Csányoszró": "Baranya",
  "Diósviszló": "Baranya",
  "Drávacsehi": "Baranya",
  "Drávapiski": "Baranya",
  "Erdősmárok": "Baranya",
  "Kisharsány": "Baranya",
  "Kistapolca": "Baranya",
  "Kistótfalu": "Baranya",
  "Kovácshida": "Baranya",
  "Magyarbóly": "Baranya",
  "Magyarszék": "Baranya",
  "Nagybudmér": "Baranya",
  "Nagydobsza": "Baranya",
  "Nagyhajmás": "Baranya",
  "Nagynyárád": "Baranya",
  "Nagypeterd": "Baranya",
  "Pécsbagota": "Baranya",
  "Pécsudvard": "Baranya",
  "Sósvertike": "Baranya",
  "Szederkény": "Baranya",
  "Szentdénes": "Baranya",
  "Vásárosbéc": "Baranya",
  "Abaújalpár": "Borsod-Abaúj-Zemplén",
  "Alsódobsza": "Borsod-Abaúj-Zemplén",
  "Alsóregmec": "Borsod-Abaúj-Zemplén",
  "Alsóvadász": "Borsod-Abaúj-Zemplén",
  "Alsózsolca": "Borsod-Abaúj-Zemplén",
  "Bánhorváti": "Borsod-Abaúj-Zemplén",
  "Becskeháza": "Borsod-Abaúj-Zemplén",
  "Bódvalenke": "Borsod-Abaúj-Zemplén",
  "Borsodbóta": "Borsod-Abaúj-Zemplén",
  "Bükkábrány": "Borsod-Abaúj-Zemplén",
  "Cserépfalu": "Borsod-Abaúj-Zemplén",
  "Farkaslyuk": "Borsod-Abaúj-Zemplén",
  "Göncruszka": "Borsod-Abaúj-Zemplén",
  "Hernádcéce": "Borsod-Abaúj-Zemplén",
  "Hidvégardó": "Borsod-Abaúj-Zemplén",
  "Járdánháza": "Borsod-Abaúj-Zemplén",
  "Keresztéte": "Borsod-Abaúj-Zemplén",
  "Kesznyéten": "Borsod-Abaúj-Zemplén",
  "Kisrozvágy": "Borsod-Abaúj-Zemplén",
  "Kissikátor": "Borsod-Abaúj-Zemplén",
  "Ládbesenyő": "Borsod-Abaúj-Zemplén",
  "Mezőnyárád": "Borsod-Abaúj-Zemplén",
  "Mezőzombor": "Borsod-Abaúj-Zemplén",
  "Mogyoróska": "Borsod-Abaúj-Zemplén",
  "Nagykinizs": "Borsod-Abaúj-Zemplén",
  "Ormosbánya": "Borsod-Abaúj-Zemplén",
  "Pusztafalu": "Borsod-Abaúj-Zemplén",
  "Sajóbábony": "Borsod-Abaúj-Zemplén",
  "Sajógalgóc": "Borsod-Abaúj-Zemplén",
  "Sajóivánka": "Borsod-Abaúj-Zemplén",
  "Sajómercse": "Borsod-Abaúj-Zemplén",
  "Sajónémeti": "Borsod-Abaúj-Zemplén",
  "Sajószöged": "Borsod-Abaúj-Zemplén",
  "Sajóvelezd": "Borsod-Abaúj-Zemplén",
  "Sóstófalva": "Borsod-Abaúj-Zemplén",
  "Szalaszend": "Borsod-Abaúj-Zemplén",
  "Szendrőlád": "Borsod-Abaúj-Zemplén",
  "Szőlősardó": "Borsod-Abaúj-Zemplén",
  "Szuhakálló": "Borsod-Abaúj-Zemplén",
  "Taktakenéz": "Borsod-Abaúj-Zemplén",
  "Taktaszada": "Borsod-Abaúj-Zemplén",
  "Telkibánya": "Borsod-Abaúj-Zemplén",
  "Tiszakarád": "Borsod-Abaúj-Zemplén",
  "Tiszakeszi": "Borsod-Abaúj-Zemplén",
  "Újcsanálos": "Borsod-Abaúj-Zemplén",
  "Vilyvitány": "Borsod-Abaúj-Zemplén",
  "Zádorfalva": "Borsod-Abaúj-Zemplén",
  "Árpádhalom": "Csongrád-Csanád",
  "Ásotthalom": "Csongrád-Csanád",
  "Csanytelek": "Csongrád-Csanád",
  "Klárafalva": "Csongrád-Csanád",
  "Nagymágocs": "Csongrád-Csanád",
  "Pusztaszer": "Csongrád-Csanád",
  "Zákányszék": "Csongrád-Csanád",
  "Bakonykúti": "Fejér",
  "Csákberény": "Fejér",
  "Előszállás": "Fejér",
  "Kisapostag": "Fejér",
  "Kőszárhegy": "Fejér",
  "Mátyásdomb": "Fejér",
  "Mezőszilas": "Fejér",
  "Nagyvenyim": "Fejér",
  "Seregélyes": "Fejér",
  "Vértesacsa": "Fejér",
  "Bácsalmás": "Bács-Kiskun",
  "Budakeszi": "Pest",
  "Dévaványa": "Békés",
  "Dunakeszi": "Pest",
  "Dunavecse": "Bács-Kiskun",
  "Esztergom": "Komárom-Esztergom",
  "Kecskemét": "Bács-Kiskun",
  "Keszthely": "Zala",
  "Nagykőrös": "Pest",
  "Szeghalom": "Békés",
  "Szekszárd": "Tolna",
  "Szigetvár": "Baranya",
  "Tatabánya": "Komárom-Esztergom",
  "Várpalota": "Veszprém",
  "Mórahalom": "Csongrád-Csanád",
  "Sárbogárd": "Fejér",
  "Kunhegyes": "Jász-Nagykun-Szolnok",
  "Oroszlány": "Komárom-Esztergom",
  "Nagykálló": "Szabolcs-Szatmár-Bereg",
  "Nyírbátor": "Szabolcs-Szatmár-Bereg",
  "Zalakaros": "Zala",
  "Almásháza": "Zala",
  "Alsópáhok": "Zala",
  "Baktüttös": "Zala",
  "Barlahida": "Zala",
  "Becsehely": "Zala",
  "Belsősárd": "Zala",
  "Csesztreg": "Zala",
  "Felsőrajk": "Zala",
  "Kerecseny": "Zala",
  "Kissziget": "Zala",
  "Külsősárd": "Zala",
  "Lasztonya": "Zala",
  "Márokföld": "Zala",
  "Milejszeg": "Zala",
  "Murarátka": "Zala",
  "Nagygörbő": "Zala",
  "Nagykutas": "Zala",
  "Nagyrécse": "Zala",
  "Nemesrádó": "Zala",
  "Németfalu": "Zala",
  "Ormándlak": "Zala",
  "Orosztony": "Zala",
  "Pálfiszeg": "Zala",
  "Pölöskefő": "Zala",
  "Sármellék": "Zala",
  "Szepetnek": "Zala",
  "Zalaapáti": "Zala",
  "Zalabaksa": "Zala",
  "Zalacsány": "Zala",
  "Zalakomár": "Zala",
  "Zalaújlak": "Zala",
  "Bácsbokod": "Bács-Kiskun",
  "Ballószög": "Bács-Kiskun",
  "Dunafalva": "Bács-Kiskun",
  "Dunapataj": "Bács-Kiskun",
  "Fülöpháza": "Bács-Kiskun",
  "Homokmégy": "Bács-Kiskun",
  "Kaskantyú": "Bács-Kiskun",
  "Kunbaracs": "Bács-Kiskun",
  "Kunpeszér": "Bács-Kiskun",
  "Lakitelek": "Bács-Kiskun",
  "Mátételke": "Bács-Kiskun",
  "Városföld": "Bács-Kiskun",
  "Dencsháza": "Baranya",
  "Geresdlak": "Baranya",
  "Hetvehely": "Baranya",
  "Himesháza": "Baranya",
  "Ivándárda": "Baranya",
  "Kétújfalu": "Baranya",
  "Kisbudmér": "Baranya",
  "Kisdobsza": "Baranya",
  "Kishajmás": "Baranya",
  "Kisherend": "Baranya",
  "Kisnyárád": "Baranya",
  "Kistamási": "Baranya",
  "Kisvaszar": "Baranya",
  "Nagycsány": "Baranya",
  "Nagykozár": "Baranya",
  "Okorvölgy": "Baranya",
  "Pécsvárad": "Baranya",
  "Sátorhely": "Baranya",
  "Szalatnak": "Baranya",
  "Szentegát": "Baranya",
  "Teklafalu": "Baranya",
  "Alsószuha": "Borsod-Abaúj-Zemplén",
  "Bódvarákó": "Borsod-Abaúj-Zemplén",
  "Bükkzsérc": "Borsod-Abaúj-Zemplén",
  "Dubicsány": "Borsod-Abaúj-Zemplén",
  "Erdőbénye": "Borsod-Abaúj-Zemplén",
  "Felsőgagy": "Borsod-Abaúj-Zemplén",
  "Filkeháza": "Borsod-Abaúj-Zemplén",
  "Fulókércs": "Borsod-Abaúj-Zemplén",
  "Gagyapáti": "Borsod-Abaúj-Zemplén",
  "Gagybátor": "Borsod-Abaúj-Zemplén",
  "Háromhuta": "Borsod-Abaúj-Zemplén",
  "Hercegkút": "Borsod-Abaúj-Zemplén",
  "Hernádbűd": "Borsod-Abaúj-Zemplén",
  "Hernádkak": "Borsod-Abaúj-Zemplén",
  "Hollóháza": "Borsod-Abaúj-Zemplén",
  "Izsófalva": "Borsod-Abaúj-Zemplén",
  "Kiskinizs": "Borsod-Abaúj-Zemplén",
  "Lácacséke": "Borsod-Abaúj-Zemplén",
  "Nagybarca": "Borsod-Abaúj-Zemplén",
  "Nagycsécs": "Borsod-Abaúj-Zemplén",
  "Nekézseny": "Borsod-Abaúj-Zemplén",
  "Nemesbikk": "Borsod-Abaúj-Zemplén",
  "Parasznya": "Borsod-Abaúj-Zemplén",
  "Radostyán": "Borsod-Abaúj-Zemplén",
  "Répáshuta": "Borsod-Abaúj-Zemplén",
  "Rudabánya": "Borsod-Abaúj-Zemplén",
  "Sajóecseg": "Borsod-Abaúj-Zemplén",
  "Sajópetri": "Borsod-Abaúj-Zemplén",
  "Sajósenye": "Borsod-Abaúj-Zemplén",
  "Sajóvámos": "Borsod-Abaúj-Zemplén",
  "Szegilong": "Borsod-Abaúj-Zemplén",
  "Szinpetri": "Borsod-Abaúj-Zemplén",
  "Szögliget": "Borsod-Abaúj-Zemplén",
  "Tiszavalk": "Borsod-Abaúj-Zemplén",
  "Vágáshuta": "Borsod-Abaúj-Zemplén",
  "Vajdácska": "Borsod-Abaúj-Zemplén",
  "Apátfalva": "Csongrád-Csanád",
  "Forráskút": "Csongrád-Csanád",
  "Kiszombor": "Csongrád-Csanád",
  "Kübekháza": "Csongrád-Csanád",
  "Maroslele": "Csongrád-Csanád",
  "Mindszent": "Csongrád-Csanád",
  "Székkutas": "Csongrád-Csanád",
  "Tömörkény": "Csongrád-Csanád",
  "Mezőfalva": "Fejér",
  "Nagyveleg": "Fejér",
  "Pusztavám": "Fejér",
  "Bátaszék": "Tolna",
  "Battonya": "Békés",
  "Csongrád": "Csongrád-Csanád",
  "Debrecen": "Hajdú-Bihar",
  "Demecser": "Szabolcs-Szatmár-Bereg",
  "Derecske": "Hajdú-Bihar",
  "Devecser": "Veszprém",
  "Dombóvár": "Tolna",
  "Gyöngyös": "Heves",
  "Kaposvár": "Somogy",
  "Kisvárda": "Szabolcs-Szatmár-Bereg",
  "Orosháza": "Békés",
  "Veszprém": "Veszprém",
  "Kiskőrös": "Bács-Kiskun",
  "Szerencs": "Borsod-Abaúj-Zemplén",
  "Mezőcsát": "Borsod-Abaúj-Zemplén",
  "Kistelek": "Csongrád-Csanád",
  "Szécsény": "Nógrád",
  "Nagykáta": "Pest",
  "Nagyatád": "Somogy",
  "Alibánfa": "Zala",
  "Alsórajk": "Zala",
  "Bocfölde": "Zala",
  "Bödeháza": "Zala",
  "Bókaháza": "Zala",
  "Börzönce": "Zala",
  "Csömödér": "Zala",
  "Fityeház": "Zala",
  "Galambok": "Zala",
  "Garabonc": "Zala",
  "Gosztola": "Zala",
  "Kacorlak": "Zala",
  "Kányavár": "Zala",
  "Kisbucsa": "Zala",
  "Kiscsehi": "Zala",
  "Kisgörbő": "Zala",
  "Kiskutas": "Zala",
  "Kisrécse": "Zala",
  "Mihályfa": "Zala",
  "Nagypáli": "Zala",
  "Nagyrada": "Zala",
  "Nemesbük": "Zala",
  "Nemesnép": "Zala",
  "Ortaháza": "Zala",
  "Ozmánbük": "Zala",
  "Salomvár": "Zala",
  "Szilvágy": "Zala",
  "Valkonya": "Zala",
  "Várfölde": "Zala",
  "Várvölgy": "Zala",
  "Zalacséb": "Zala",
  "Zalalövő": "Zala",
  "Csátalja": "Bács-Kiskun",
  "Csikéria": "Bács-Kiskun",
  "Drágszél": "Bács-Kiskun",
  "Géderlak": "Bács-Kiskun",
  "Helvécia": "Bács-Kiskun",
  "Imrehegy": "Bács-Kiskun",
  "Kunadacs": "Bács-Kiskun",
  "Móricgát": "Bács-Kiskun",
  "Orgovány": "Bács-Kiskun",
  "Szeremle": "Bács-Kiskun",
  "Tataháza": "Bács-Kiskun",
  "Abaliget": "Baranya",
  "Bánhalma": "Baranya",
  "Beremend": "Baranya",
  "Csarnóta": "Baranya",
  "Drávafok": "Baranya",
  "Erzsébet": "Baranya",
  "Gerényes": "Baranya",
  "Gilvánfa": "Baranya",
  "Görcsöny": "Baranya",
  "Gyöngyfa": "Baranya",
  "Illocska": "Baranya",
  "Kiskassa": "Baranya",
  "Kislippó": "Baranya",
  "Lánycsók": "Baranya",
  "Lapáncsa": "Baranya",
  "Martonfa": "Baranya",
  "Mekényes": "Baranya",
  "Monyoród": "Baranya",
  "Nagypall": "Baranya",
  "Nagyváty": "Baranya",
  "Palkonya": "Baranya",
  "Rádfalva": "Baranya",
  "Somberek": "Baranya",
  "Szalánta": "Baranya",
  "Szaporca": "Baranya",
  "Szászvár": "Baranya",
  "Szulimán": "Baranya",
  "Abaújkér": "Borsod-Abaúj-Zemplén",
  "Abaújlak": "Borsod-Abaúj-Zemplén",
  "Abaújvár": "Borsod-Abaúj-Zemplén",
  "Aggtelek": "Borsod-Abaúj-Zemplén",
  "Alsógagy": "Borsod-Abaúj-Zemplén",
  "Baktakék": "Borsod-Abaúj-Zemplén",
  "Csenyéte": "Borsod-Abaúj-Zemplén",
  "Csernely": "Borsod-Abaúj-Zemplén",
  "Domaháza": "Borsod-Abaúj-Zemplén",
  "Egerlövő": "Borsod-Abaúj-Zemplén",
  "Égerszög": "Borsod-Abaúj-Zemplén",
  "Gesztely": "Borsod-Abaúj-Zemplén",
  "Hejőbába": "Borsod-Abaúj-Zemplén",
  "Hejőkürt": "Borsod-Abaúj-Zemplén",
  "Hejőpapi": "Borsod-Abaúj-Zemplén",
  "Jákfalva": "Borsod-Abaúj-Zemplén",
  "Kázsmárk": "Borsod-Abaúj-Zemplén",
  "Kiscsécs": "Borsod-Abaúj-Zemplén",
  "Kistokaj": "Borsod-Abaúj-Zemplén",
  "Komlóska": "Borsod-Abaúj-Zemplén",
  "Kurityán": "Borsod-Abaúj-Zemplén",
  "Mályinka": "Borsod-Abaúj-Zemplén",
  "Martonyi": "Borsod-Abaúj-Zemplén",
  "Megyaszó": "Borsod-Abaúj-Zemplén",
  "Mikóháza": "Borsod-Abaúj-Zemplén",
  "Nagyhuta": "Borsod-Abaúj-Zemplén",
  "Sajókaza": "Borsod-Abaúj-Zemplén",
  "Sajóörös": "Borsod-Abaúj-Zemplén",
  "Szakácsi": "Borsod-Abaúj-Zemplén",
  "Szalonna": "Borsod-Abaúj-Zemplén",
  "Szomolya": "Borsod-Abaúj-Zemplén",
  "Taktabáj": "Borsod-Abaúj-Zemplén",
  "Tiszalúc": "Borsod-Abaúj-Zemplén",
  "Balástya": "Csongrád-Csanád",
  "Csengele": "Csongrád-Csanád",
  "Domaszék": "Csongrád-Csanád",
  "Nagytőke": "Csongrád-Csanád",
  "Óföldeák": "Csongrád-Csanád",
  "Pitvaros": "Csongrád-Csanád",
  "Szatymaz": "Csongrád-Csanád",
  "Baracska": "Fejér",
  "Isztimér": "Fejér",
  "Polgárdi": "Fejér",
  "Rácalmás": "Fejér",
  "Sáregres": "Fejér",
  "Sárkeszi": "Fejér",
  "Bábolna": "Komárom-Esztergom",
  "Balkány": "Szabolcs-Szatmár-Bereg",
  "Berhida": "Veszprém",
  "Bonyhád": "Tolna",
  "Budaörs": "Pest",
  "Csákvár": "Fejér",
  "Csepreg": "Vas",
  "Csorvás": "Békés",
  "Dombrád": "Szabolcs-Szatmár-Bereg",
  "Edelény": "Borsod-Abaúj-Zemplén",
  "Gárdony": "Fejér",
  "Gödöllő": "Pest",
  "Kalocsa": "Bács-Kiskun",
  "Komárom": "Komárom-Esztergom",
  "Körmend": "Vas",
  "Marcali": "Somogy",
  "Mezőtúr": "Jász-Nagykun-Szolnok",
  "Miskolc": "Borsod-Abaúj-Zemplén",
  "Szarvas": "Békés",
  "Szentes": "Csongrád-Csanád",
  "Szolnok": "Jász-Nagykun-Szolnok",
  "Tapolca": "Veszprém",
  "Szikszó": "Borsod-Abaúj-Zemplén",
  "Kapuvár": "Győr-Moson-Sopron",
  "Túrkeve": "Jász-Nagykun-Szolnok",
  "Ráckeve": "Pest",
  "Solymár": "Pest",
  "Kemecse": "Szabolcs-Szatmár-Bereg",
  "Letenye": "Zala",
  "Belezna": "Zala",
  "Bezeréd": "Zala",
  "Bucsuta": "Zala",
  "Dióskál": "Zala",
  "Döbröce": "Zala",
  "Egervár": "Zala",
  "Hernyék": "Zala",
  "Iborfia": "Zala",
  "Kallósd": "Zala",
  "Kálócfa": "Zala",
  "Karmacs": "Zala",
  "Keménfa": "Zala",
  "Kilimán": "Zala",
  "Kispáli": "Zala",
  "Lakhegy": "Zala",
  "Lovászi": "Zala",
  "Molnári": "Zala",
  "Pölöske": "Zala",
  "Pötréte": "Zala",
  "Ramocsa": "Zala",
  "Resznek": "Zala",
  "Sárhida": "Zala",
  "Szalapa": "Zala",
  "Teskánd": "Zala",
  "Újudvar": "Zala",
  "Vöckönd": "Zala",
  "Zalabér": "Zala",
  "Zalavár": "Zala",
  "Zalavég": "Zala",
  "Zebecke": "Zala",
  "Akasztó": "Bács-Kiskun",
  "Apostag": "Bács-Kiskun",
  "Csávoly": "Bács-Kiskun",
  "Csengőd": "Bács-Kiskun",
  "Katymár": "Bács-Kiskun",
  "Kelebia": "Bács-Kiskun",
  "Kunbaja": "Bács-Kiskun",
  "Madaras": "Bács-Kiskun",
  "Mélykút": "Bács-Kiskun",
  "Szakmár": "Bács-Kiskun",
  "Tiszaug": "Bács-Kiskun",
  "Újtelek": "Bács-Kiskun",
  "Adorjás": "Baranya",
  "Bakonya": "Baranya",
  "Berkesd": "Baranya",
  "Besence": "Baranya",
  "Bezedek": "Baranya",
  "Bicsérd": "Baranya",
  "Bogdása": "Baranya",
  "Bükkösd": "Baranya",
  "Csebény": "Baranya",
  "Cserkút": "Baranya",
  "Gordisa": "Baranya",
  "Harkány": "Baranya",
  "Hásságy": "Baranya",
  "Helesfa": "Baranya",
  "Homorúd": "Baranya",
  "Husztót": "Baranya",
  "Ipacsfa": "Baranya",
  "Kacsóta": "Baranya",
  "Katádfa": "Baranya",
  "Köblény": "Baranya",
  "Lothárd": "Baranya",
  "Marócsa": "Baranya",
  "Merenye": "Baranya",
  "Molvány": "Baranya",
  "Nemeske": "Baranya",
  "Oroszló": "Baranya",
  "Ózdfalu": "Baranya",
  "Pellérd": "Baranya",
  "Pereked": "Baranya",
  "Pettend": "Baranya",
  "Regenye": "Baranya",
  "Romonya": "Baranya",
  "Rózsafa": "Baranya",
  "Szárász": "Baranya",
  "Szebény": "Baranya",
  "Szemely": "Baranya",
  "Szilágy": "Baranya",
  "Szilvás": "Baranya",
  "Szörény": "Baranya",
  "Tengeri": "Baranya",
  "Tésenfa": "Baranya",
  "Újpetre": "Baranya",
  "Vajszló": "Baranya",
  "Vázsnok": "Baranya",
  "Versend": "Baranya",
  "Villány": "Baranya",
  "Alacska": "Borsod-Abaúj-Zemplén",
  "Bánréve": "Borsod-Abaúj-Zemplén",
  "Berente": "Borsod-Abaúj-Zemplén",
  "Csincse": "Borsod-Abaúj-Zemplén",
  "Debréte": "Borsod-Abaúj-Zemplén",
  "Fancsal": "Borsod-Abaúj-Zemplén",
  "Galvács": "Borsod-Abaúj-Zemplén",
  "Garadna": "Borsod-Abaúj-Zemplén",
  "Girincs": "Borsod-Abaúj-Zemplén",
  "Hangács": "Borsod-Abaúj-Zemplén",
  "Hangony": "Borsod-Abaúj-Zemplén",
  "Harsány": "Borsod-Abaúj-Zemplén",
  "Hegymeg": "Borsod-Abaúj-Zemplén",
  "Homrogd": "Borsod-Abaúj-Zemplén",
  "Jósvafő": "Borsod-Abaúj-Zemplén",
  "Kelemér": "Borsod-Abaúj-Zemplén",
  "Kenézlő": "Borsod-Abaúj-Zemplén",
  "Kisgyőr": "Borsod-Abaúj-Zemplén",
  "Kishuta": "Borsod-Abaúj-Zemplén",
  "Komjáti": "Borsod-Abaúj-Zemplén",
  "Múcsony": "Borsod-Abaúj-Zemplén",
  "Pálháza": "Borsod-Abaúj-Zemplén",
  "Pamlény": "Borsod-Abaúj-Zemplén",
  "Perecse": "Borsod-Abaúj-Zemplén",
  "Perkupa": "Borsod-Abaúj-Zemplén",
  "Sajólád": "Borsod-Abaúj-Zemplén",
  "Szakáld": "Borsod-Abaúj-Zemplén",
  "Szászfa": "Borsod-Abaúj-Zemplén",
  "Szemere": "Borsod-Abaúj-Zemplén",
  "Szendrő": "Borsod-Abaúj-Zemplén",
  "Szuhafő": "Borsod-Abaúj-Zemplén",
  "Szuhogy": "Borsod-Abaúj-Zemplén",
  "Tardona": "Borsod-Abaúj-Zemplén",
  "Tolcsva": "Borsod-Abaúj-Zemplén",
  "Vilmány": "Borsod-Abaúj-Zemplén",
  "Vizsoly": "Borsod-Abaúj-Zemplén",
  "Bordány": "Csongrád-Csanád",
  "Eperjes": "Csongrád-Csanád",
  "Földeák": "Csongrád-Csanád",
  "Mártély": "Csongrád-Csanád",
  "Nagylak": "Csongrád-Csanád",
  "Öttömös": "Csongrád-Csanád",
  "Szegvár": "Csongrád-Csanád",
  "Balinka": "Fejér",
  "Csókakő": "Fejér",
  "Felcsút": "Fejér",
  "Iváncsa": "Fejér",
  "Kajászó": "Fejér",
  "Kisláng": "Fejér",
  "Lepsény": "Fejér",
  "Nagylók": "Fejér",
  "Pázmánd": "Fejér",
  "Perkáta": "Fejér",
  "Soponya": "Fejér",
  "Újbarok": "Fejér",
  "Velence": "Fejér",
  "Bicske": "Fejér",
  "Bodajk": "Fejér",
  "Cegléd": "Pest",
  "Cigánd": "Borsod-Abaúj-Zemplén",
  "Csorna": "Győr-Moson-Sopron",
  "Csurgó": "Somogy",
  "Enying": "Fejér",
  "Fonyód": "Somogy",
  "Hatvan": "Heves",
  "Ibrány": "Szabolcs-Szatmár-Bereg",
  "Karcag": "Jász-Nagykun-Szolnok",
  "Kőszeg": "Vas",
  "Mohács": "Baranya",
  "Sárvár": "Vas",
  "Siófok": "Somogy",
  "Sopron": "Győr-Moson-Sopron",
  "Szeged": "Csongrád-Csanád",
  "Sellye": "Baranya",
  "Siklós": "Baranya",
  "Putnok": "Borsod-Abaúj-Zemplén",
  "Sarkad": "Békés",
  "Kisbér": "Komárom-Esztergom",
  "Rétság": "Nógrád",
  "Pásztó": "Nógrád",
  "Vecsés": "Pest",
  "Tamási": "Tolna",
  "Vasvár": "Vas",
  "Baglad": "Zala",
  "Bocska": "Zala",
  "Borsfa": "Zala",
  "Csatár": "Zala",
  "Gyűrűs": "Zala",
  "Miháld": "Zala",
  "Misefa": "Zala",
  "Oltárc": "Zala",
  "Rédics": "Zala",
  "Rigyác": "Zala",
  "Söjtör": "Zala",
  "Sormás": "Zala",
  "Vállus": "Zala",
  "Vaspör": "Zala",
  "Borota": "Bács-Kiskun",
  "Dusnok": "Bács-Kiskun",
  "Kömpöc": "Bács-Kiskun",
  "Sükösd": "Bács-Kiskun",
  "Tázlár": "Bács-Kiskun",
  "Újsolt": "Bács-Kiskun",
  "Vaskút": "Bács-Kiskun",
  "Babarc": "Baranya",
  "Bakóca": "Baranya",
  "Birján": "Baranya",
  "Borjád": "Baranya",
  "Cserdi": "Baranya",
  "Csertő": "Baranya",
  "Egerág": "Baranya",
  "Ellend": "Baranya",
  "Endrőc": "Baranya",
  "Hirics": "Baranya",
  "Kákics": "Baranya",
  "Kárász": "Baranya",
  "Kátoly": "Baranya",
  "Kékesd": "Baranya",
  "Kisdér": "Baranya",
  "Kökény": "Baranya",
  "Kölked": "Baranya",
  "Liptód": "Baranya",
  "Lúzsok": "Baranya",
  "Mágocs": "Baranya",
  "Maráza": "Baranya",
  "Markóc": "Baranya",
  "Mozsgó": "Baranya",
  "Óbánya": "Baranya",
  "Ócsárd": "Baranya",
  "Okorág": "Baranya",
  "Páprád": "Baranya",
  "Peterd": "Baranya",
  "Pogány": "Baranya",
  "Sumony": "Baranya",
  "Szellő": "Baranya",
  "Szőkéd": "Baranya",
  "Tarrós": "Baranya",
  "Téseny": "Baranya",
  "Tormás": "Baranya",
  "Töttös": "Baranya",
  "Túrony": "Baranya",
  "Vékény": "Baranya",
  "Velény": "Baranya",
  "Véménd": "Baranya",
  "Vokány": "Baranya",
  "Zaláta": "Baranya",
  "Ároktő": "Borsod-Abaúj-Zemplén",
  "Aszaló": "Borsod-Abaúj-Zemplén",
  "Balajt": "Borsod-Abaúj-Zemplén",
  "Bekecs": "Borsod-Abaúj-Zemplén",
  "Berzék": "Borsod-Abaúj-Zemplén",
  "Bogács": "Borsod-Abaúj-Zemplén",
  "Boldva": "Borsod-Abaúj-Zemplén",
  "Bózsva": "Borsod-Abaúj-Zemplén",
  "Büttös": "Borsod-Abaúj-Zemplén",
  "Csobád": "Borsod-Abaúj-Zemplén",
  "Csobaj": "Borsod-Abaúj-Zemplén",
  "Dövény": "Borsod-Abaúj-Zemplén",
  "Halmaj": "Borsod-Abaúj-Zemplén",
  "Igrici": "Borsod-Abaúj-Zemplén",
  "Ináncs": "Borsod-Abaúj-Zemplén",
  "Karcsa": "Borsod-Abaúj-Zemplén",
  "Királd": "Borsod-Abaúj-Zemplén",
  "Korlát": "Borsod-Abaúj-Zemplén",
  "Meszes": "Borsod-Abaúj-Zemplén",
  "Négyes": "Borsod-Abaúj-Zemplén",
  "Nyésta": "Borsod-Abaúj-Zemplén",
  "Nyomár": "Borsod-Abaúj-Zemplén",
  "Oszlár": "Borsod-Abaúj-Zemplén",
  "Pányok": "Borsod-Abaúj-Zemplén",
  "Ragály": "Borsod-Abaúj-Zemplén",
  "Rakaca": "Borsod-Abaúj-Zemplén",
  "Selyeb": "Borsod-Abaúj-Zemplén",
  "Semjén": "Borsod-Abaúj-Zemplén",
  "Tállya": "Borsod-Abaúj-Zemplén",
  "Tarcal": "Borsod-Abaúj-Zemplén",
  "Uppony": "Borsod-Abaúj-Zemplén",
  "Varbóc": "Borsod-Abaúj-Zemplén",
  "Viszló": "Borsod-Abaúj-Zemplén",
  "Zalkod": "Borsod-Abaúj-Zemplén",
  "Zsujta": "Borsod-Abaúj-Zemplén",
  "Zubogy": "Borsod-Abaúj-Zemplén",
  "Felgyő": "Csongrád-Csanád",
  "Kövegy": "Csongrád-Csanád",
  "Nagyér": "Csongrád-Csanád",
  "Röszke": "Csongrád-Csanád",
  "Zsombó": "Csongrád-Csanád",
  "Baracs": "Fejér",
  "Besnyő": "Fejér",
  "Bodmér": "Fejér",
  "Csabdi": "Fejér",
  "Hantos": "Fejér",
  "Óbarok": "Fejér",
  "Pákozd": "Fejér",
  "Sárosd": "Fejér",
  "Sukoró": "Fejér",
  "Tabajd": "Fejér",
  "Tordas": "Fejér",
  "Úrhida": "Fejér",
  "Zámoly": "Fejér",
  "Abony": "Pest",
  "Adony": "Fejér",
  "Aszód": "Pest",
  "Barcs": "Somogy",
  "Békés": "Békés",
  "Beled": "Győr-Moson-Sopron",
  "Bugac": "Bács-Kiskun",
  "Dabas": "Pest",
  "Diósd": "Pest",
  "Dorog": "Komárom-Esztergom",
  "Gyula": "Békés",
  "Heves": "Heves",
  "Hévíz": "Zala",
  "Kecel": "Bács-Kiskun",
  "Komló": "Baranya",
  "Monor": "Pest",
  "Sümeg": "Veszprém",
  "Lenti": "Zala",
  "Bagod": "Zala",
  "Batyk": "Zala",
  "Csapi": "Zala",
  "Csöde": "Zala",
  "Dobri": "Zala",
  "Gelse": "Zala",
  "Gétye": "Zala",
  "Gősfa": "Zala",
  "Hahót": "Zala",
  "Hottó": "Zala",
  "Kávás": "Zala",
  "Liszó": "Zala",
  "Maróc": "Zala",
  "Pacsa": "Zala",
  "Padár": "Zala",
  "Pakod": "Zala",
  "Sénye": "Zala",
  "Tilaj": "Zala",
  "Tófej": "Zala",
  "Türje": "Zala",
  "Bátya": "Bács-Kiskun",
  "Bócsa": "Bács-Kiskun",
  "Dávod": "Bács-Kiskun",
  "Fajsz": "Bács-Kiskun",
  "Foktő": "Bács-Kiskun",
  "Gátér": "Bács-Kiskun",
  "Hajós": "Bács-Kiskun",
  "Harta": "Bács-Kiskun",
  "Izsák": "Bács-Kiskun",
  "Miske": "Bács-Kiskun",
  "Ordas": "Bács-Kiskun",
  "Pirtó": "Bács-Kiskun",
  "Szank": "Bács-Kiskun",
  "Tabdi": "Bács-Kiskun",
  "Tompa": "Bács-Kiskun",
  "Uszód": "Bács-Kiskun",
  "Zsana": "Bács-Kiskun",
  "Baksa": "Baranya",
  "Bánfa": "Baranya",
  "Basal": "Baranya",
  "Bikal": "Baranya",
  "Bisse": "Baranya",
  "Bogád": "Baranya",
  "Bosta": "Baranya",
  "Bürüs": "Baranya",
  "Feked": "Baranya",
  "Gerde": "Baranya",
  "Gödre": "Baranya",
  "Hidas": "Baranya",
  "Hobol": "Baranya",
  "Ibafa": "Baranya",
  "Kásád": "Baranya",
  "Kémes": "Baranya",
  "Kemse": "Baranya",
  "Keszü": "Baranya",
  "Kórós": "Baranya",
  "Liget": "Baranya",
  "Lippó": "Baranya",
  "Mánfa": "Baranya",
  "Márfa": "Baranya",
  "Márok": "Baranya",
  "Matty": "Baranya",
  "Meződ": "Baranya",
  "Ófalu": "Baranya",
  "Olasz": "Baranya",
  "Piskó": "Baranya",
  "Pócsa": "Baranya",
  "Sámod": "Baranya",
  "Sárok": "Baranya",
  "Szágy": "Baranya",
  "Szajk": "Baranya",
  "Szava": "Baranya",
  "Szőke": "Baranya",
  "Tékes": "Baranya",
  "Udvar": "Baranya",
  "Várad": "Baranya",
  "Varga": "Baranya",
  "Vejti": "Baranya",
  "Zádor": "Baranya",
  "Arnót": "Borsod-Abaúj-Zemplén",
  "Baskó": "Borsod-Abaúj-Zemplén",
  "Beret": "Borsod-Abaúj-Zemplén",
  "Damak": "Borsod-Abaúj-Zemplén",
  "Dámóc": "Borsod-Abaúj-Zemplén",
  "Detek": "Borsod-Abaúj-Zemplén",
  "Forró": "Borsod-Abaúj-Zemplén",
  "Füzér": "Borsod-Abaúj-Zemplén",
  "Gadna": "Borsod-Abaúj-Zemplén",
  "Gelej": "Borsod-Abaúj-Zemplén",
  "Golop": "Borsod-Abaúj-Zemplén",
  "Hejce": "Borsod-Abaúj-Zemplén",
  "Imola": "Borsod-Abaúj-Zemplén",
  "Irota": "Borsod-Abaúj-Zemplén",
  "Karos": "Borsod-Abaúj-Zemplén",
  "Kéked": "Borsod-Abaúj-Zemplén",
  "Kondó": "Borsod-Abaúj-Zemplén",
  "Köröm": "Borsod-Abaúj-Zemplén",
  "Litka": "Borsod-Abaúj-Zemplén",
  "Mályi": "Borsod-Abaúj-Zemplén",
  "Monaj": "Borsod-Abaúj-Zemplén",
  "Monok": "Borsod-Abaúj-Zemplén",
  "Nyíri": "Borsod-Abaúj-Zemplén",
  "Pácin": "Borsod-Abaúj-Zemplén",
  "Prügy": "Borsod-Abaúj-Zemplén",
  "Rátka": "Borsod-Abaúj-Zemplén",
  "Regéc": "Borsod-Abaúj-Zemplén",
  "Ricse": "Borsod-Abaúj-Zemplén",
  "Szegi": "Borsod-Abaúj-Zemplén",
  "Tokaj": "Borsod-Abaúj-Zemplén",
  "Tomor": "Borsod-Abaúj-Zemplén",
  "Trizs": "Borsod-Abaúj-Zemplén",
  "Vadna": "Borsod-Abaúj-Zemplén",
  "Varbó": "Borsod-Abaúj-Zemplén",
  "Vatta": "Borsod-Abaúj-Zemplén",
  "Ziliz": "Borsod-Abaúj-Zemplén",
  "Algyő": "Csongrád-Csanád",
  "Deszk": "Csongrád-Csanád",
  "Ruzsa": "Csongrád-Csanád",
  "Üllés": "Csongrád-Csanád",
  "Agárd": "Fejér",
  "Csősz": "Fejér",
  "Ercsi": "Fejér",
  "Etyek": "Fejér",
  "Gyúró": "Fejér",
  "Káloz": "Fejér",
  "Kulcs": "Fejér",
  "Nadap": "Fejér",
  "Pátka": "Fejér",
  "Söréd": "Fejér",
  "Vajta": "Fejér",
  "Vereb": "Fejér",
  "Ajka": "Veszprém",
  "Baja": "Bács-Kiskun",
  "Bóly": "Baranya",
  "Eger": "Heves",
  "Elek": "Békés",
  "Emőd": "Borsod-Abaúj-Zemplén",
  "Encs": "Borsod-Abaúj-Zemplén",
  "Gönc": "Borsod-Abaúj-Zemplén",
  "Gyál": "Pest",
  "Győr": "Győr-Moson-Sopron",
  "Makó": "Csongrád-Csanád",
  "Paks": "Tolna",
  "Pápa": "Veszprém",
  "Pécs": "Baranya",
  "Tata": "Komárom-Esztergom",
  "Zirc": "Veszprém",
  "Sásd": "Baranya",
  "Böde": "Zala",
  "Dötk": "Zala",
  "Nova": "Zala",
  "Páka": "Zala",
  "Rezi": "Zala",
  "Sand": "Zala",
  "Surd": "Zala",
  "Zajk": "Zala",
  "Gara": "Bács-Kiskun",
  "Páhi": "Bács-Kiskun",
  "Solt": "Bács-Kiskun",
  "Tass": "Bács-Kiskun",
  "Boda": "Baranya",
  "Garé": "Baranya",
  "Gyód": "Baranya",
  "Majs": "Baranya",
  "Máza": "Baranya",
  "Orfű": "Baranya",
  "Palé": "Baranya",
  "Szűr": "Baranya",
  "Tófű": "Baranya",
  "Abod": "Borsod-Abaúj-Zemplén",
  "Arka": "Borsod-Abaúj-Zemplén",
  "Arló": "Borsod-Abaúj-Zemplén",
  "Bőcs": "Borsod-Abaúj-Zemplén",
  "Fony": "Borsod-Abaúj-Zemplén",
  "Kács": "Borsod-Abaúj-Zemplén",
  "Kánó": "Borsod-Abaúj-Zemplén",
  "Kány": "Borsod-Abaúj-Zemplén",
  "Kupa": "Borsod-Abaúj-Zemplén",
  "Méra": "Borsod-Abaúj-Zemplén",
  "Muhi": "Borsod-Abaúj-Zemplén",
  "Onga": "Borsod-Abaúj-Zemplén",
  "Ónod": "Borsod-Abaúj-Zemplén",
  "Pere": "Borsod-Abaúj-Zemplén",
  "Sály": "Borsod-Abaúj-Zemplén",
  "Sáta": "Borsod-Abaúj-Zemplén",
  "Sima": "Borsod-Abaúj-Zemplén",
  "Szin": "Borsod-Abaúj-Zemplén",
  "Tard": "Borsod-Abaúj-Zemplén",
  "Viss": "Borsod-Abaúj-Zemplén",
  "Baks": "Csongrád-Csanád",
  "Alap": "Fejér",
  "Cece": "Fejér",
  "Csór": "Fejér",
  "Füle": "Fejér",
  "Gánt": "Fejér",
  "Igar": "Fejér",
  "Jenő": "Fejér",
  "Mány": "Fejér",
  "Moha": "Fejér",
  "Szár": "Fejér",
  "Aba": "Fejér",
  "Ács": "Komárom-Esztergom",
  "Érd": "Pest",
  "Mór": "Fejér",
  "Ózd": "Borsod-Abaúj-Zemplén",
  "Vác": "Pest",
  "Tét": "Győr-Moson-Sopron",
  "Tab": "Somogy",
  "Vép": "Vas",
  "Bak": "Zala",
  "Pat": "Zala",
  "Rém": "Bács-Kiskun",
  "Áta": "Baranya",
  "Bár": "Baranya",
  "Cún": "Baranya",
  "Old": "Baranya",
  "Zók": "Baranya",
  "Fáj": "Borsod-Abaúj-Zemplén",
  "Hét": "Borsod-Abaúj-Zemplén",
  "Lak": "Borsod-Abaúj-Zemplén",
  "Léh": "Borsod-Abaúj-Zemplén",
  "Mád": "Borsod-Abaúj-Zemplén",
  "Dóc": "Csongrád-Csanád",
  "Dég": "Fejér",
  "Tác": "Fejér",
  "Vál": "Fejér",
  "Ág": "Baranya"

};

const MAX_ITEMS = 400;

const SETTLEMENT_NAMES = Object.keys(SETTLEMENT_COUNTY);

const SYSTEM_PROMPT =
  "Du bist ein präziser Übersetzer für amtliche ungarische Notfall- und Katastrophenschutzmeldungen. " +
  "Übersetze Titel und Beschreibung sachlich und exakt ins Deutsche, ohne Fakten hinzuzufügen oder wegzulassen. " +
  "Behalte Ortsnamen und Straßennamen im ungarischen Original bei. " +
  "Antworte NUR mit einem JSON-Objekt in der Form {\"title\":\"...\",\"description\":\"...\"}, " +
  "ohne Markdown-Codeblock, ohne zusätzlichen Text.";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === "/api/events") {
      return handleEventsApi(env);
    }

    if (url.pathname === "/api/admin-stats") {
      return handleAdminStats(request, env);
    }

    // 🆕 24.8.: Einfacher Seitenaufrufe-Zähler fürs Melovista-Admin-Dashboard
    // (siehe handleAdminStats() unten). Zählt nur echte Seitenaufrufe
    // (HTML-Seiten), nicht jede JS/CSS/Bild-Anfrage. Läuft über
    // ctx.waitUntil() im Hintergrund - verzögert die eigentliche
    // Seitenauslieferung also nicht.
    if (url.pathname === "/" || url.pathname.endsWith(".html")) {
      ctx.waitUntil(recordPageview(env));
    }

    return env.ASSETS.fetch(request);
  },

  async scheduled(event, env, ctx) {
    ctx.waitUntil(updateEvents(env));
  }
};

// ------------------------------------------------------------
// Seitenaufrufe-Zähler (für Melovista-Admin-Dashboard)
// ------------------------------------------------------------
// Bewusst einfach gehalten: KV ist nicht atomar, unter hoher
// Gleichzeitigkeit können einzelne Zählungen verloren gehen - für die
// erwartete Nutzerzahl dieser Nebenprojekt-App unkritisch, es geht um
// eine grobe Größenordnung, nicht um Abrechnungsgenauigkeit.
async function recordPageview(env) {
  try {
    const today = new Date().toISOString().slice(0, 10); // "YYYY-MM-DD"

    const totalRaw = await env.VESZ_KV.get("pageviews:total");
    const total = (parseInt(totalRaw, 10) || 0) + 1;
    await env.VESZ_KV.put("pageviews:total", String(total));

    const dailyRaw = await env.VESZ_KV.get("pageviews:daily", { type: "json" });
    const daily = dailyRaw || {};
    daily[today] = (daily[today] || 0) + 1;

    // Auf die letzten 30 Tage begrenzen, damit der KV-Wert nicht unbegrenzt wächst
    const days = Object.keys(daily).sort();
    while (days.length > 30) {
      delete daily[days.shift()];
    }

    await env.VESZ_KV.put("pageviews:daily", JSON.stringify(daily));
  } catch (e) {
    // Zähler ist nice-to-have, darf die eigentliche Seitenauslieferung
    // nie beeinträchtigen.
    console.log("Pageview-Zähler-Fehler:", e);
  }
}

// ------------------------------------------------------------
// Admin-Stats-Endpunkt (für Melovista-Admin-Dashboard)
// ------------------------------------------------------------
// Diese App hat bewusst kein eigenes Login-System (siehe Übergabe-Doku).
// Schutz hier deshalb über ein gemeinsames Geheimnis (ADMIN_STATS_SECRET
// als Cloudflare-Secret bei DIESEM Worker), das der Melovista-Worker beim
// Abfragen mitschicken muss - selbst gewählter, zufälliger String, kein
// Melovista-Passwort wiederverwenden.
async function handleAdminStats(request, env) {
  const url = new URL(request.url);
  const key = url.searchParams.get("key");

  if (!env.ADMIN_STATS_SECRET || key !== env.ADMIN_STATS_SECRET) {
    return new Response(JSON.stringify({ error: "not_authorized" }), {
      status: 403,
      headers: { "content-type": "application/json; charset=utf-8" }
    });
  }

  const totalRaw = await env.VESZ_KV.get("pageviews:total");
  const total = parseInt(totalRaw, 10) || 0;

  const dailyRaw = await env.VESZ_KV.get("pageviews:daily", { type: "json" });
  const daily = dailyRaw || {};

  const today = new Date().toISOString().slice(0, 10);
  const todayCount = daily[today] || 0;

  // Letzte 7 Tage aufsummieren (inkl. heute) für einen groben Trend
  const days = Object.keys(daily).sort().slice(-7);
  const last7Days = days.reduce((sum, d) => sum + (daily[d] || 0), 0);

  return new Response(JSON.stringify({
    totalPageviews: total,
    todayPageviews: todayCount,
    last7DaysPageviews: last7Days,
    daily
  }), {
    headers: { "content-type": "application/json; charset=utf-8" }
  });
}

// ------------------------------------------------------------
// API-Antwort
// ------------------------------------------------------------
async function handleEventsApi(env) {
  const index = (await env.VESZ_KV.get("index", { type: "json" })) || [];
  return new Response(JSON.stringify(index), {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=60",
      "access-control-allow-origin": "*"
    }
  });
}

// ------------------------------------------------------------
// Haupt-Update-Routine (läuft per Cron alle 10 Minuten)
// ------------------------------------------------------------
async function updateEvents(env) {
  const existingIndex = (await env.VESZ_KV.get("index", { type: "json" })) || [];
  const indexMap = new Map(existingIndex.map((entry) => [entry.id, entry]));

  // Nationalen Feed laden
  let nationalItems = [];
  try {
    const res = await fetch(NATIONAL_RSS);
    if (res.ok) nationalItems = parseRSS(await res.text());
  } catch (e) {
    console.log("Fehler beim Laden des nationalen Feeds:", e);
  }

  const currentIds = new Set();

  for (const item of nationalItems) {
    const id = extractEventId(item.link);
    currentIds.add(id);

    if (indexMap.has(id)) {
      indexMap.get(id).active = true;
      continue;
    }

    // Neues Ereignis -> übersetzen
    const category = categorize(item.title, item.description);
    const locationHint = await fetchHelyszin(item.link);
    const county = guessCounty(item.title, item.description, locationHint);
    const translated = await translateEvent(item.title, item.description, env);

    indexMap.set(id, {
      id,
      link: item.link,
      pubDate: item.pubDate,
      title_hu: item.title,
      description_hu: item.description,
      title_de: translated.title,
      description_de: translated.description,
      category,
      county,
      active: true,
      firstSeen: new Date().toISOString()
    });
  }

  // Ereignisse, die nicht mehr im aktuellen Feed sind -> archivieren
  for (const [id, entry] of indexMap) {
    if (!currentIds.has(id)) entry.active = false;
  }

  const newIndex = Array.from(indexMap.values())
    .sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate))
    .slice(0, MAX_ITEMS);

  await env.VESZ_KV.put("index", JSON.stringify(newIndex));
}

// ------------------------------------------------------------
// Landkreis-Erkennung anhand des Texts (BM OKF "Landkreis-Feeds" sind
// KEINE echten regionalen Feeds - sie spiegeln alle denselben
// landesweiten Datenstrom, deshalb bringt eine separate Abfrage keinen
// Mehrwert. Stattdessen: nach expliziter Nennung im Text suchen,
// ehrlich "Landesweit", wenn nichts gefunden wird.
// ------------------------------------------------------------
async function fetchHelyszin(url) {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const html = await res.text();
    const text = html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
    const match = text.match(/Helyszín:\s*([^,<]+)/i);
    return match ? match[1].trim() : null;
  } catch (e) {
    return null;
  }
}

function guessCounty(title, description, locationHint) {
  const text = `${title} ${description}`;

  if (/f[őö]v[aá]rosi|budapest/i.test(text)) return "Budapest";

  // Zuerst das saubere "Helyszín"-Feld der Einzelseite prüfen, falls vorhanden
  // (zuverlässiger als der Fließtext: keine Fallendungen, keine Nebenerwähnungen)
  if (locationHint) {
    for (const settlement of SETTLEMENT_NAMES) {
      const pattern = new RegExp(`\\b${escapeRegex(settlement)}`, "i");
      if (pattern.test(locationHint)) return SETTLEMENT_COUNTY[settlement];
    }
  }

  // Zuerst nach bekannten Orten im Fließtext suchen (genauer als die vármegyei-Textsuche).
  // Nur linke Wortgrenze prüfen, da ungarische Fallendungen (-nál, -ban, -tól, ...)
  // direkt ohne Leerzeichen angehängt werden (z.B. "Hajdúnánásnál").
  for (const settlement of SETTLEMENT_NAMES) {
    const pattern = new RegExp(`\\b${escapeRegex(settlement)}`, "i");
    if (pattern.test(text)) return SETTLEMENT_COUNTY[settlement];
  }

  for (const name of COUNTY_NAMES) {
    const pattern = new RegExp(`${escapeRegex(name)}\\s+v[aá]rmegy`, "i");
    if (pattern.test(text)) return name;
  }

  return "Landesweit";
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ------------------------------------------------------------
// Übersetzung per OpenRouter
// ------------------------------------------------------------
async function translateEvent(titleHu, descriptionHu, env) {
  const model = env.OPENROUTER_MODEL || "openai/gpt-4o-mini";

  try {
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model,
        temperature: 0.2,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: `Titel: ${titleHu}\nBeschreibung: ${descriptionHu}` }
        ]
      })
    });

    if (!res.ok) {
      console.log("OpenRouter Fehler:", res.status, await res.text());
      return { title: titleHu, description: descriptionHu };
    }

    const data = await res.json();
    const raw = (data.choices?.[0]?.message?.content || "").trim();
    const cleaned = raw.replace(/^```json\s*/i, "").replace(/```$/, "").trim();
    const parsed = JSON.parse(cleaned);

    return {
      title: parsed.title || titleHu,
      description: parsed.description || descriptionHu
    };
  } catch (e) {
    console.log("Übersetzungsfehler:", e);
    return { title: titleHu, description: descriptionHu };
  }
}

// ------------------------------------------------------------
// Kategorisierung (Typ des Ereignisses anhand des Textes)
// ------------------------------------------------------------
function categorize(title, description) {
  const text = `${title} ${description}`.toLowerCase();

  if (/(tűz|égett|égés|lángol|kigyulladt|gyulladt)/.test(text)) return "feuer";
  if (/(baleset|karambol|ütközött|gázolás|árokba|felborult|borult)/.test(text)) return "unfall";
  if (/(riasztás|meteorológ|hőség|vihar|árvíz|jégeső|hóhelyzet)/.test(text)) return "wetter";
  return "sonstiges";
}

// ------------------------------------------------------------
// Einfacher RSS-Parser (kein XML-DOM nötig, da Feed einfach aufgebaut ist)
// ------------------------------------------------------------
function parseRSS(xml) {
  const items = [];
  const blocks = xml.match(/<item>[\s\S]*?<\/item>/g) || [];

  for (const block of blocks) {
    const title = extractTag(block, "title");
    const link = extractTag(block, "link");
    const description = extractTag(block, "description");
    const pubDate = extractTag(block, "pubDate");
    if (title && link) items.push({ title, link, description, pubDate });
  }

  return items;
}

function extractTag(block, tag) {
  const match = block.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`));
  if (!match) return "";
  let value = match[1].trim();

  const cdata = value.match(/^<!\[CDATA\[([\s\S]*)\]\]>$/);
  if (cdata) value = cdata[1];

  return decodeEntities(value);
}

function decodeEntities(str) {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&apos;/g, "'");
}

function extractEventId(link) {
  const match = link.match(/\/esemeny\/(\d+)/);
  return match ? match[1] : link;
}
